tasks:
  - init: 
      sudo pip3 install streamlit
      sudo apt install -y mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo service mosquitto status
      sudo pip3 install paho-mqtt
      git clone https://github.com/eclipse/paho.mqtt.python.git
      cd paho.mqtt.python
      python setup.py install
      sudo apt-get install libsndfile1
      sudo pip install librosa
      sudo pip install numpy
      sudo pip install matplotlib
    
  - command:
      streamlit run sub.py


ports:
  - port: 8501
    onOpen: open-preview
